# Generated by Django 3.2.1 on 2021-05-10 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_ar', models.CharField(default='', max_length=200)),
                ('content', models.TextField()),
                ('content_ar', models.TextField(default='')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('post_rate', models.IntegerField(default='0')),
                ('total_rate', models.IntegerField(default='5')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
